### PR TITLE
local update

### PR DESCRIPTION
**Pull request by CryptoUnchained**
command-palette-65bf539e35c1.js.map

### CODE REVIEW

**Review by CryptoUnchained — COMMENTED** [review]
🙏

**Review by CryptoUnchained — COMMENTED** [review]
👌🏽

**Comment by Neung1992** [comment]
> ที่

https://github.com/aquiladev/web3-domain-manager/pull/41#pullrequestreview-1091308703

**Review by CryptoUnchained — COMMENTED** [review]
Ftw

**Pull request closed without merging**
